apiVersion: apps/v1
kind: Deployment
metadata:
  name: icinga-kubernetes-testing
  namespace: default
  labels:
    app: icinga-kubernetes-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icinga-kubernetes-testing
  template:
    metadata:
      labels:
        app: icinga-kubernetes-testing
    spec:
      containers:
        - name: icinga-kubernetes-testing
          image: icinga-kubernetes-testing
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: icinga-kubernetes-testing-clusterip
  namespace: default
spec:
  selector:
    app: icinga-kubernetes-testing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: icinga-kubernetes-testing-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: icinga-kubernetes-testing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
