apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tests.icinga.com
spec:
  group: icinga.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                containers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      imagePullPolicy:
                        type: string
                      ports:
                        type: array
                        items:
                          type: object
                          properties:
                            containerPort:
                              type: integer
                            name:
                              type: string
                      readinessProbe:
                        type: object
                        properties:
                          httpGet:
                            type: object
                            properties:
                              path:
                                type: string
                              port:
                                type: integer
                      livenessProbe:
                        type: object
                        properties:
                          httpGet:
                            type: object
                            properties:
                              path:
                                type: string
                              port:
                                type: integer
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
  scope: Namespaced
  names:
    kind: Test
    listKind: TestList
    plural: tests
    singular: test
    shortNames:
      - tst
