apiVersion: v1
kind: Pod
metadata:
  name: icinga-for-kubernetes-testing-tester
  namespace: testing
  labels:
    icingaForKubernetesTesting: 1
spec:
  containers:
    - name: icinga-for-kubernetes-testing-tester
      image: ikt-tester
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          name: http
#      readinessProbe:
#        httpGet:
#          path: /readiness
#          port: 8080
#        initialDelaySeconds: 5
#        periodSeconds: 10
#      livenessProbe:
#        httpGet:
#          path: /liveness
#          port: 8080
#        initialDelaySeconds: 15
#        periodSeconds: 20
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
