// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/icinga/icinga-kubernetes-testing/pkg/apis/icinga/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TestLister helps list Tests.
// All objects returned here must be treated as read-only.
type TestLister interface {
	// List lists all Tests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Test, err error)
	// Tests returns an object that can list and get Tests.
	Tests(namespace string) TestNamespaceLister
	TestListerExpansion
}

// testLister implements the TestLister interface.
type testLister struct {
	indexer cache.Indexer
}

// NewTestLister returns a new TestLister.
func NewTestLister(indexer cache.Indexer) TestLister {
	return &testLister{indexer: indexer}
}

// List lists all Tests in the indexer.
func (s *testLister) List(selector labels.Selector) (ret []*v1.Test, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Test))
	})
	return ret, err
}

// Tests returns an object that can list and get Tests.
func (s *testLister) Tests(namespace string) TestNamespaceLister {
	return testNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TestNamespaceLister helps list and get Tests.
// All objects returned here must be treated as read-only.
type TestNamespaceLister interface {
	// List lists all Tests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Test, err error)
	// Get retrieves the Test from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Test, error)
	TestNamespaceListerExpansion
}

// testNamespaceLister implements the TestNamespaceLister
// interface.
type testNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Tests in the indexer for a given namespace.
func (s testNamespaceLister) List(selector labels.Selector) (ret []*v1.Test, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Test))
	})
	return ret, err
}

// Get retrieves the Test from the indexer for a given namespace and name.
func (s testNamespaceLister) Get(name string) (*v1.Test, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("test"), name)
	}
	return obj.(*v1.Test), nil
}
