// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	icingav1 "github.com/icinga/icinga-kubernetes-testing/pkg/apis/icinga/applyconfiguration/icinga/v1"
	v1 "github.com/icinga/icinga-kubernetes-testing/pkg/apis/icinga/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=icinga.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("Test"):
		return &icingav1.TestApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("TestSpec"):
		return &icingav1.TestSpecApplyConfiguration{}

	}
	return nil
}
