// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/icinga/icinga-kubernetes-testing/pkg/apis/icinga/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTests implements TestInterface
type FakeTests struct {
	Fake *FakeIcingaV1
	ns   string
}

var testsResource = v1.SchemeGroupVersion.WithResource("tests")

var testsKind = v1.SchemeGroupVersion.WithKind("Test")

// Get takes name of the test, and returns the corresponding test object, and an error if there is any.
func (c *FakeTests) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testsResource, c.ns, name), &v1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Test), err
}

// List takes label and field selectors, and returns the list of Tests that match those selectors.
func (c *FakeTests) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testsResource, testsKind, c.ns, opts), &v1.TestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TestList{ListMeta: obj.(*v1.TestList).ListMeta}
	for _, item := range obj.(*v1.TestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tests.
func (c *FakeTests) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testsResource, c.ns, opts))

}

// Create takes the representation of a test and creates it.  Returns the server's representation of the test, and an error, if there is any.
func (c *FakeTests) Create(ctx context.Context, test *v1.Test, opts metav1.CreateOptions) (result *v1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testsResource, c.ns, test), &v1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Test), err
}

// Update takes the representation of a test and updates it. Returns the server's representation of the test, and an error, if there is any.
func (c *FakeTests) Update(ctx context.Context, test *v1.Test, opts metav1.UpdateOptions) (result *v1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testsResource, c.ns, test), &v1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Test), err
}

// Delete takes name of the test and deletes it. Returns an error if one occurs.
func (c *FakeTests) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(testsResource, c.ns, name, opts), &v1.Test{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTests) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TestList{})
	return err
}

// Patch applies the patch and returns the patched test.
func (c *FakeTests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testsResource, c.ns, name, pt, data, subresources...), &v1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Test), err
}
